version: "3"
services:
  enum-batch-gen:
    build:
      context: .
      dockerfile: ./enum-batch-gen/Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - SQS_QUEUE_URL=https://sqs.us-east-1.amazonaws.com/110303772622/key-enumerator-batches
      - START=22381000
      - BATCH_SIZE=1000
  enum:
    build:
      context: ./enum
      dockerfile: ./Dockerfile
    environment:
      - QUEUER_HOSTNAME=queuer
      - QUEUER_PORT=3000
      - STARTING_VALUE=100000
    depends_on:
      - queuer
  queuer:
    build:
      context: .
      dockerfile: ./queuer/Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - PORT=3000
  recorder:
    build:
      context: .
      dockerfile: ./recorder/Dockerfile
    environment:
      - PGHOST=db
      - PGDATABASE=keys
      - PGUSER=pguser
      - PGPASSWORD=mqjwDUBaomAwXQwl
      - PGSSLMODE=disable
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    depends_on:
      - db
  db:
    image: postgres:9.6
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=keys
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=mqjwDUBaomAwXQwl
    volumes:
      - "./pgdata:/var/lib/postgresql/data/pgdata"
