version: "3"
services:
  enum:
    build:
      context: ./enum
      dockerfile: ./Dockerfile
    depends_on:
      - queuer
  queuer:
    build:
      context: .
      dockerfile: ./queuer/Dockerfile
    ports:
      - "3000:3000"