version: "3"
services:
  enum-batch-gen:
    build:
      context: .
      dockerfile: ./enum-batch-gen/Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - BATCH_QUEUE_URL
      - START=34400000
      - BATCH_SIZE=20000
  enum:
    build:
      context: ./enum
      dockerfile: ./Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - BATCH_QUEUE_URL
      - QUEUER_HOSTNAME=queuer
      - QUEUER_PORT=3000
    depends_on:
      - queuer
  queuer:
    build:
      context: .
      dockerfile: ./queuer/Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - KEY_QUEUE_URL
      - PORT=3000
  recorder:
    build:
      context: .
      dockerfile: ./recorder/Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - KEY_QUEUE_URL
      - PGHOST
      - PGDATABASE
      - PGUSER
      - PGPASSWORD
